import bmwImg from "#/assets/images/car-bmw.jpg";
import ferrariImg from "#/assets/images/car-ferrari.jpg";
import mercedesImg from "#/assets/images/car-mercedes.jpg";
import rangeroverImg from "#/assets/images/car-rangerover.jpg";
import rollsImg from "#/assets/images/car-rolls.jpg";
import teslaImg from "#/assets/images/car-tesla.jpg";
import type { Booking, Car } from "#/types";

const d = (offset: number) => {
	const today = new Date();
	const x = new Date(today);

	x.setDate(x.getDate() + offset);
	return x.toISOString().slice(0, 10);
};

export const bookings: Booking[] = [
	{
		id: "B-1042",
		carId: "c1",
		customer: "Alex Morgan",
		customerEmail: "alex@mail.com",
		customerPhone: "+1 555 1234",
		type: "rent",
		start: d(-30),
		end: d(-25),
		pickupAt: `${d(-30)} 10:00`,
		dropoffAt: `${d(-25)} 18:00`,
		pickup: "Downtown Office",
		dropoff: "Downtown Office",
		total: 1100,
		status: "completed",
		createdAt: d(-40),
		passengers: 2,
		licenseNumber: "D-9921-MA",
		licenseCountry: "USA",
		mileageLimit: 200,
		fuelPolicy: "full_to_full",
		extras: [
			{
				id: "gps",
				name: "GPS Navigation",
				priceType: "per_day",
				price: 5,
				qty: 5,
			},
		],
	},
	{
		id: "B-1051",
		carId: "c2",
		customer: "Priya Shah",
		customerEmail: "priya@mail.com",
		customerPhone: "+1 555 2222",
		type: "wedding",
		start: d(-12),
		end: d(-12),
		total: 900,
		status: "completed",
		createdAt: d(-25),
		passengers: 4,
		extras: [
			{
				id: "flowers",
				name: "Flower Decoration",
				priceType: "per_booking",
				price: 40,
			},
			{
				id: "photog",
				name: "Onboard Photographer",
				priceType: "per_trip",
				price: 150,
			},
		],
	},
	{
		id: "B-1063",
		carId: "c3",
		customer: "Marco Bianchi",
		customerEmail: "marco@mail.com",
		customerPhone: "+39 333 9090",
		type: "rent",
		start: d(-3),
		end: d(2),
		pickupAt: `${d(-3)} 09:00`,
		dropoffAt: `${d(2)} 09:00`,
		pickup: "Airport Counter",
		dropoff: "Airport Counter",
		total: 6000,
		status: "ongoing",
		createdAt: d(-10),
		passengers: 2,
		licenseNumber: "IT-887-MI",
		licenseCountry: "Italy",
		mileageLimit: 300,
		fuelPolicy: "full_to_full",
		delivery: true,
		deliveryAddress: "Hotel Excelsior Lobby",
		specialRequests: "Please leave keys with concierge.",
		extras: [
			{
				id: "wifi",
				name: "WiFi Hotspot",
				priceType: "per_day",
				price: 8,
				qty: 5,
			},
			{
				id: "zero-exc",
				name: "Zero Excess Insurance",
				priceType: "per_day",
				price: 25,
				qty: 5,
			},
		],
	},
	{
		id: "B-1070",
		carId: "c5",
		customer: "Sara Klein",
		customerEmail: "sara@mail.com",
		customerPhone: "+49 170 5050",
		type: "transfer",
		start: d(1),
		end: d(1),
		pickup: "JFK Airport",
		dropoff: "Ritz-Carlton NY",
		pickupAt: `${d(1)} 14:30`,
		total: 400,
		status: "confirmed",
		createdAt: d(-2),
		withDriver: true,
		passengers: 3,
		extras: [
			{
				id: "meet",
				name: "Meet & Greet Sign",
				priceType: "per_trip",
				price: 10,
			},
			{
				id: "champagne",
				name: "Champagne & Snacks",
				priceType: "per_trip",
				price: 50,
			},
		],
	},
	{
		id: "B-1071",
		carId: "c1",
		customer: "James Patel",
		customerEmail: "james@mail.com",
		customerPhone: "+44 7700 9",
		type: "rent",
		start: d(4),
		end: d(9),
		pickupAt: `${d(4)} 11:00`,
		dropoffAt: `${d(9)} 11:00`,
		pickup: "Downtown Office",
		dropoff: "Airport Counter",
		total: 1100,
		status: "pending",
		createdAt: d(-1),
		passengers: 1,
		licenseNumber: "UK-771-LN",
		licenseCountry: "United Kingdom",
		oneWay: true,
		mileageLimit: 250,
		fuelPolicy: "full_to_full",
		extras: [
			{
				id: "gps",
				name: "GPS Navigation",
				priceType: "per_day",
				price: 5,
				qty: 5,
			},
		],
	},
	{
		id: "B-1072",
		carId: "c2",
		customer: "Olivia Brun",
		customerEmail: "olivia@mail.com",
		customerPhone: "+33 6 11 22",
		type: "wedding",
		start: d(6),
		end: d(6),
		total: 900,
		status: "pending",
		createdAt: d(0),
		passengers: 5,
		specialRequests: "White ribbon, classical music playlist.",
	},
	{
		id: "B-1073",
		carId: "c5",
		customer: "Hassan Aziz",
		customerEmail: "hassan@mail.com",
		customerPhone: "+971 50 111",
		type: "event",
		start: d(10),
		end: d(11),
		total: 8000,
		status: "confirmed",
		createdAt: d(-3),
		passengers: 4,
		extras: [
			{
				id: "carpet",
				name: "Red Carpet Service",
				priceType: "per_trip",
				price: 25,
			},
		],
	},
	{
		id: "B-1074",
		carId: "c3",
		customer: "Leo Tanaka",
		customerEmail: "leo@mail.com",
		customerPhone: "+81 90 555",
		type: "event",
		start: d(15),
		end: d(15),
		total: 2500,
		status: "pending",
		createdAt: d(0),
		passengers: 2,
	},
	{
		id: "B-1075",
		carId: "c4",
		customer: "Nadia Carter",
		customerEmail: "nadia@mail.com",
		customerPhone: "+1 555 7777",
		type: "transfer",
		start: d(2),
		end: d(2),
		pickup: "LAX Terminal 4",
		dropoff: "Beverly Hills Hotel",
		pickupAt: `${d(2)} 21:15`,
		total: 150,
		status: "rejected",
		createdAt: d(-1),
		withDriver: true,
		passengers: 2,
		extras: [
			{
				id: "child",
				name: "Child Seat",
				priceType: "per_day",
				price: 10,
				qty: 1,
			},
		],
	},
];

export const cars: Car[] = [
	{
		id: "c1",
		make: "Tesla",
		model: "Model S",
		year: 2023,
		color: "Black",
		plate: "TSL-001",
		image: teslaImg,
		status: "active",
		services: ["rent", "transfer"],
		dailyRate: 220,
		transferRate: 90,
		seats: 5,
		transmission: "Auto",
		fuel: "Electric",
		features: ["WiFi", "Autopilot", "Premium Audio", "Sunroof"],
	},
	{
		id: "c2",
		make: "Mercedes-Benz",
		model: "S-Class",
		year: 2024,
		color: "White",
		plate: "MRC-204",
		image: mercedesImg,
		status: "active",
		services: ["rent", "transfer", "wedding"],
		dailyRate: 350,
		transferRate: 120,
		weddingRate: 900,
		seats: 5,
		transmission: "Auto",
		fuel: "Hybrid",
		features: ["Leather", "Massage Seats", "Chauffeur Pack"],
	},
	{
		id: "c3",
		make: "Ferrari",
		model: "488 GTB",
		year: 2022,
		color: "Red",
		plate: "FRR-488",
		image: ferrariImg,
		status: "active",
		services: ["rent", "event"],
		dailyRate: 1200,
		eventRate: 2500,
		seats: 2,
		transmission: "Auto",
		fuel: "Petrol",
		features: ["Carbon Pack", "Sport Mode", "Launch Control"],
	},
	{
		id: "c4",
		make: "Range Rover",
		model: "Vogue",
		year: 2023,
		color: "Black",
		plate: "RNG-770",
		image: rangeroverImg,
		status: "maintenance",
		services: ["rent", "transfer", "event"],
		dailyRate: 420,
		transferRate: 150,
		eventRate: 1200,
		seats: 7,
		transmission: "Auto",
		fuel: "Diesel",
		features: ["4x4", "Panoramic Roof", "Rear Entertainment"],
	},
	{
		id: "c5",
		make: "Rolls-Royce",
		model: "Ghost",
		year: 2024,
		color: "Silver",
		plate: "RLS-001",
		image: rollsImg,
		status: "active",
		services: ["wedding", "event", "transfer"],
		dailyRate: 1500,
		transferRate: 400,
		weddingRate: 3500,
		eventRate: 4000,
		seats: 5,
		transmission: "Auto",
		fuel: "Petrol",
		features: ["Starlight Roof", "Champagne Cooler", "Rear Suicide Doors"],
	},
	{
		id: "c6",
		make: "BMW",
		model: "7 Series",
		year: 2023,
		color: "White",
		plate: "BMW-701",
		image: bmwImg,
		status: "inactive",
		services: ["rent", "transfer"],
		dailyRate: 280,
		transferRate: 100,
		seats: 5,
		transmission: "Auto",
		fuel: "Hybrid",
		features: ["Executive Lounge", "Gesture Control"],
	},
];

export const revenueChart = [
  { month: "Jan", rent: 6500, transfer: 2200, wedding: 1800, event: 900 },
  { month: "Feb", rent: 7200, transfer: 2900, wedding: 2100, event: 1500 },
  { month: "Mar", rent: 8400, transfer: 3300, wedding: 2700, event: 2300 },
  { month: "Apr", rent: 9100, transfer: 3500, wedding: 3000, event: 2700 },
  { month: "May", rent: 10500, transfer: 4100, wedding: 3500, event: 3200 },
  { month: "Jun", rent: 11800, transfer: 4400, wedding: 4000, event: 3800 },
  { month: "Jul", rent: 12900, transfer: 4900, wedding: 4400, event: 4200 },
];